/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-04-30 05:06:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Webchat</title>\r\n");
      out.write("    <script src=\"https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("    <link href=\"favicon.ico\" rel=\"shortcut icon\" />\r\n");
      out.write("    <link href=\"https://cdn.bootcss.com/twitter-bootstrap/3.4.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\" background: url(https://cdn.jsdelivr.net/gh/Ac1d-0-0/blog_img/static_files/img/index.png) no-repeat center center fixed; background-size: 100%;\">\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("    <div class=\"modal-dialog\" style=\"margin-top: 10%;\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write(" \r\n");
      out.write("                <h4 class=\"modal-title text-center\" id=\"myModalLabel\">登录</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form method=\"post\" action=\"/Webchat/user/login\" enctype=\"application/x-www-form-urlencoded\">\r\n");
      out.write("            <div class=\"modal-body\" id = \"model-body\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write("                    <input id=\"id\" type=\"text\" required=\"required\" name=\"UserID\" class=\"form-control\"placeholder=\"用户名\" autocomplete=\"off\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write(" \r\n");
      out.write("                    <input id=\"pass\" type=\"password\" required=\"required\" name=\"Password\" class=\"form-control\" placeholder=\"密码\" autocomplete=\"off\">\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <button id=\"login\" type=\"button\" class=\"btn btn-primary form-control\">登录</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <button id = \"register\" type=\"button\" class=\"btn btn-default form-control\">注册</button>\r\n");
      out.write("                </div>\r\n");
      out.write(" \r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div><!-- /.modal-content -->\r\n");
      out.write("    </div><!-- /.modal -->\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $(\"#login\").click(function () {\r\n");
      out.write("\t\t\t\t\tvar id=document.getElementById(\"id\");\r\n");
      out.write("\t\t\t\t\tvar pass=document.getElementById(\"pass\");\r\n");
      out.write("\t\t\t\t\talert(\"hello\");\r\n");
      out.write("\t\t            $.ajax({\r\n");
      out.write("\t\t                type: \"POST\",\r\n");
      out.write("\t\t                url: \"/Webchat/user/login\",\r\n");
      out.write("\t\t                data: {\r\n");
      out.write("\t\t                    UserID: id,\r\n");
      out.write("\t\t                    pass: pass,\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                success: function (data) {\r\n");
      out.write("\t\t                    if (data == \"false\") {\r\n");
      out.write("\t\t                        alert(\"用户名或密码错误\");\r\n");
      out.write("\t\t                    }\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            });\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t$(\"#register\").click(function () {\r\n");
      out.write("\t\t\t\t\t\t\tvar id=document.getElementById(\"id\");\r\n");
      out.write("\t\t\t\t\t\t\tvar pass=document.getElementById(\"pass\");\r\n");
      out.write("\t\t\t\t\t\t\talert(\"hi\");\r\n");
      out.write("\t\t           $.ajax({\r\n");
      out.write("\t\t               type: \"POST\",\r\n");
      out.write("\t\t               url: \"/Webchat/user/register\",\r\n");
      out.write("\t\t               data: {\r\n");
      out.write("\t\t                   UserID: id,\r\n");
      out.write("\t\t                   pass: pass,\r\n");
      out.write("\t\t               },\r\n");
      out.write("\t\t               success: function (data) {\r\n");
      out.write("\t\t                   if (data == \"false\") {\r\n");
      out.write("\t\t                       alert(\"注册失败，请重试\");\r\n");
      out.write("\t\t                   }\r\n");
      out.write("\t\t               }\r\n");
      out.write("\t\t           });\r\n");
      out.write("\t\t       });\t\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
